### ISSUE TITLE
Privacy Question : Can I Use The Editor For Sensitive Info ? 

### ISSUE THREAD

**Issue by jdevstatic** [StackExchange/Stacks-Editor#102]
Good day. 

I'm just wondering whether I can use the editor to write things that are sensitive and private, like it is my private notepad, then I'll transfer the content somewhere, I just want to write in Markdown, and this Editor is what I'm looking for.

Thanks !

**Comment by b-kelly** [comment]
The Stacks-Editor itself does not include any analytics or data harvesting code. The only features designed with networking in mind would be the image upload and link preview features, which need to have their endpoints specified by package consumers. That's the long way of saying: Yes, the package itself should be safe to use for private/sensitive content.
