### ISSUE TITLE
Suggestion: Add a repository description

### ISSUE THREAD

**Issue by sbrl** [StackExchange/Stacks-Editor#11]
**Is your feature request related to a problem? Please describe.**

When I star a repository and come back to it a few months later, I can find it difficult to remember what a repository or project was about by its name alone. Having a repository description assists me in recalling what a project actually does when it is in my list of starred projects.

In addition, it would help new users identify what the project does.

**Describe the solution you'd like**
I suggest adding a GitHub description to this repository. Maybe it could also go at the top of the README too?

**Describe alternatives you've considered**
I could build an entire custom GitHub starred projects manager in which I could have a local override..... but that seems like too much work for such a trivial problem.

**Additional context**
Came from a StackExchange blog post, but got momentarily confused as to whether I was even in the right repository or not.

**Comment by b-kelly** [comment]
Excellent idea! Thanks for the suggestion. I've added a short description to the GH repo, as well as a slightly longer description to the README.
