### ISSUE TITLE
<code> not rendered correctly; incorrectly escapes when switching

### ISSUE THREAD

**Issue by chwarr** [StackExchange/Stacks-Editor#12]
**Describe the bug**

The Stacks Editor does not properly render \<code\> elements and incorrectly escapes them when toggling from Markdown mode to rendered mode.

**To Reproduce**

1. Start a new post. Make sure you are in Markdown mode, not rendered/rich edit mode.
2. Enter the following Markdown: `<code>this should be code formatted <i>with some italics inside</i></code>`
    ![screenshot of the editor with the sample Markdown input](https://user-images.githubusercontent.com/10605667/106527465-2d24e300-649c-11eb-9465-beaf4958e792.png)
3. Click the toggle to switch to rendered/rich edit mode.
4. Click the toggle to switch back to Markdown mode.

**Expected behavior**

* After step 3, the rendered post looks like: <code>this should be code formatted with some <i>italics inside</i></code>
* After step 3, the Markdown should be exactly what was entered after step 2

**Actual behavior**

* After step 3, the rendered post has literal \<code\> and \</code\> shown. None of the sentence has typewriter formatting. The italics are shown correctly:
    ![screenshot of the incorrectly rendering output](https://user-images.githubusercontent.com/10605667/106527636-74ab6f00-649c-11eb-8528-b9c69d8ff3d6.png)
* After step 3, the Markdown has had \<code\> changed to \`\<code\>\` and similarly for \</code\>:

    ```
    `<code>`this should be code formatted <i>with some italics inside</i>`</code>`
    ```

    ![screenshot with the incorrectly escaped Markdown](https://user-images.githubusercontent.com/10605667/106527751-a15f8680-649c-11eb-8709-58579e6b839f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 85.0, Edge 88.0.705.56

**Additional context**

If I submit the answer/edit without previewing, the \<code\> elements are rendered correctly.

I first encountered this on a StackOverflow Enterprise installation. I have the same experience on Meta Stack Exchange.

**Comment by LoganDark** [comment]
I'd like to point out here that as a side effect of this bug the editor is committing a **grave sin**: entering WYSIWYG mode in this case is *changing the markup arbitrarily*, which is not what one expects to see. Changes should only be done around the cursor/selection as a result of explicit user interaction :(

Many editors do this (eBay's editor minifies all HTML), but it is not expected behavior, and I would argue that it's not correct either.

**Comment by hamvocke** [comment]
@LoganDark Leaving markdown as is when switching between markdown and rich-text mode is something we've got on our radar but haven't solved yet. I totally agree that the editor should not change your markdown existing markdown syntax.

**Comment by b-kelly** [comment]
Did some investigation, reporting here so I remember where to pick up again later:

`<code>this should be code formatted <i>with some italics inside</i></code>` parses as `[code_inline, text, em_open, text, em_close, code_inline]`.

```
`this should be code formatted <i>with some italics inside</i>`
```
is parsed as a single `code_inline` with the context set to the entire text (no html parsing).

What we're seeing is that `code_inline` does not have an `_open/_close` suffix like other marks, so the content between the bounding tokens is not wrapped in the code mark.

Easiest solution? Parse `<code>` as a different token (`code_inline_split`?) that opens/closes and is ultimately parsed to the same mark as `code_inline`.
