### ISSUE TITLE
Auto-escape detected code in Commonmark mode

### ISSUE THREAD

**Issue by b-kelly** [StackExchange/Stacks-Editor#135]
**Is your feature request related to a problem? Please describe.**

New users that are unfamiliar with Commonmark syntax are pasting code into the editor and becoming frustrated when it does not render as they expected. Additionally, rich-text mode will auto-escape restricted characters when serializing to commonmark. This makes the editing experience more frustrating when users try to fix the post's formatting.

**Describe the solution you'd like**

Text containing code pasted into Commonmark mode should be wrapped in code fences. Text is already parsed to detect code in rich-text mode, so we may be able to extend that functionality to commonmark mode.

The largest issue is that Commonmark mode uses a completely different schema than rich-text mode, which has no idea about node parsing. For every paste, we'd need to spin up a copy of the rich-text schema, parse the paste as nodes, then serialize it back to commonmark. The upside of this is that any pasted html (such as from Google Docs, etc) will get auto-translated to commonmark on paste. The downside is that users may be expecting a plain text paste. The native work around to that problem is for users to use the OS native plain text paste shortcut (ctrl-shift-v on Windows, cmd-shift-v on macOS), which strips out all non-text clipboard entries before pasting.

**Additional context**

User flow issue described on [MSO](https://meta.stackoverflow.com/questions/416801/is-the-new-editors-inline-code-tool-supposed-to-break-up-code-blocks) was used as the basis of this feature request..

**Comment by yellis** [comment]
Does this include "Putting each line of code in a separate code block e.g. [Codemirror searchfilter](https://stackoverflow.com/questions/71712228/codemirror-searchfilter)" as mentioned [here](https://meta.stackoverflow.com/q/417091/51)

**Comment by b-kelly** [comment]
@yellis Regarding the first issue... I'm not sure. That post is using _inline_ code formatting (`\``), not _code block_ formatting (`\`\`\``). I'm not sure exactly how that came to be, but I think that is different behavior than what is being addressed here.

Regarding the second, yes, that seems to be covered under this feature enhancement.

**Comment by yellis** [comment]
@b-kelly The first one is [reported here](https://meta.stackoverflow.com/questions/416801/is-the-new-editors-inline-code-tool-supposed-to-break-up-code-blocks) with replication instructions there.

**Comment by b-kelly** [comment]
@yellis Hmm... yeah, that post is what prompted me to create this issue (see my response there). The inline code syntax is the wrong tool for the job, as it is intended for placing code inline with other text. Imo, this enhancement will hopefully alleviate the confusion, but ultimately, we try to adhere to the Commonmark spec as possible (extending vs overriding when able).
