### ISSUE TITLE
Help with available options

### ISSUE THREAD

**Issue by pfms84** [StackExchange/Stacks-Editor#145]
Since there's no documentation, it's hard to configure the editor, even by browsing the code, so, I someone could help me it would be great since I have some questions.

1- Is it possible to change the text of labels, like for instance, change the help for inline code to a different language?
2- Is it possible to disable the markdown toggle and use the editor just in rich text mode?
3- Is it possible to hide/disable some options like for instance links?

Thank you very much

**Comment by b-kelly** [comment]
Thanks for your interest in the project! I've been playing with docs that autogenerate from the TS types, but haven't yet had any spare cycles to finalize the work - hopefully soon™.

In regards to your questions:

### 1 - change menu label text

I _just_ [committed localization support for menu entries](https://github.com/StackExchange/Stacks-Editor/blob/main/src/shared/localization.ts#L17-L48). This will allow you to change the text to whatever you like. We're still working on making sure localization works _everywhere_ there's text, so if you spot any places that need updating, please feel free to open an issue.

### 2 - rich-text mode only

At the moment, there's currently no way to disable markdown mode without a bit of code. Now, this is _entirely untested_ and **unsupported** (it may break in the short to near future), but you could try the following to hide the toggle:
```js
document.querySelector(".js-editor-mode-switcher").parentElement.style.setProperty("display", "none", "important")
```
Unfortunately, the code will still be loaded for the commonmark editor. The next best thing would be to use the internal `RichTextEditor` class and reimplement the menu/plugin containers manually.

This is something we _may_ officially support in the future, but it currently is not prioritized on our roadmap. If this is something you feel strongly about, please open a feature request so we can track it.

### 3 - disabling some menu items

At the moment, the only features you can enable/disable are found in the [CommonViewOptions.parserFeatures options](https://github.com/StackExchange/Stacks-Editor/blob/main/src/shared/view.ts#L65-L82). Some other options tweak the behavior of some of the menu commands, so I'd recommend giving all items in [CommonViewOptions] (https://github.com/StackExchange/Stacks-Editor/blob/main/src/shared/view.ts#L16-L40)a read. We're currently experimenting with an external plugin system that would (hopefully) allow users to deeply extend the editor, including the command menu. This system is currently *experimental* and subject to change, but I'd recommend giving it a try and letting us know in what ways it falls short.

**Comment by b-kelly** [comment]
Hopefully the above comment solves your issue. We're still planning on adding generated documentation - I even have a branch locally where I have a partial implementation / discovery. Closing for now. Please reopen if you feel that this has not yet been addressed.
