### ISSUE TITLE
Uncaught TypeError: Cannot set properties of undefined (setting 'parentContainer') at Ic.setupPluginContainer (app.bundle.js:87:17414)

### ISSUE THREAD

**Issue by yasiriqbal1990** [StackExchange/Stacks-Editor#149]
I am trying to using text editor via script tag in HTML file but I am getting this error:
Uncaught TypeError: Cannot set properties of undefined (setting 'parentContainer') at Ic.setupPluginContainer (app.bundle.js:87:17414)
Here is the code which I copied from your official docs.
    <link
      rel="stylesheet"
      src="./node_modules/@stackoverflow/stacks-editor/dist/styles.css"
    />
    <div id="editor-container"></div>

    
    <script src="https://unpkg.com/@highlightjs/cdn-assets@11.5.1/highlight.min.js"></script>

    
    <script src="./node_modules/@stackoverflow/stacks-editor/dist/app.bundle.js"></script>

    
    <script>
      new window.stacksEditor.StacksEditor(
        document.querySelector("#editor-container"),
        "*Your* **markdown** here",
        {}
      );
    </script>

**Comment by colombo15** [comment]
`
    this.options.commonmarkOptions.preview.parentContainer =
            previewContainerFn;
`

This is causing the issue when  `preview: { enabled: true }` is not set.

Either `commonmarkOptions.preview` needs to always be set by default or check if it exists before `.parentContainer = previewContainerFn;`

@b-kelly @dancormier Not sure which option you guys prefer.

**Comment by b-kelly** [comment]
I'll look into and get a fix out for this asap. Thank you for the report.
