### ISSUE TITLE
Markdown preview UX

### ISSUE THREAD

**Issue by b-kelly** [StackExchange/Stacks-Editor#150]
The markdown preview is currently laid out like the old Stack Exchange editor's preview - editor on top, preview on bottom. We should look into a way to improve the UX here, potentially making it an expandable pane, making it configurable, etc.

**Comment by yellis** [comment]
@b-kelly I am happy to take the lead on this, I just need some guidance on how to get started.

I am assuming:
- Expandable pane for preview section, with internal scrolling
- Button on editor panel to toggle it on/off (ie: even when turned on in the editor, that just makes the button visible). 
- Save value of button in cookie (for starters, can be user pref at a later date)

Questions:
1. Configurable - what types of configuration options where you thinking of? I thought it is just on or off.
2. We'd need a new icon for a button, right?
3. Do you view these integration steps as something to go into the core editor, or into a plugin?

**Comment by b-kelly** [comment]
1. There needs to be some investigation here. There's on/off ofc, but also things like "always shown", side-by-side vs above-below, etc. These probably wouldn't be included in the first pass, but it is something we'd want to think about
2. I don't know if we even want to do a button - adding a new button to the menu on _non-mobile_ causes some scrolling, so we'd potentially want to collapse other items into a menu to make room for this
  - Additionally, adding a new button would cause some menu jumping when toggling between modes
3. Whatever we decide on for options, that support would go into the editor. As far as "how to store the preference" (e.g. cookie), that should _not_ go into the editor codebase

As a side note regarding using a cookie, that would have some bureaucratic overhead as we'd need to get the cookie categorized for GDPR and other legal mumbo-jumbo.

**Comment by b-kelly** [comment]
@yellis Still planned for Beta 2 or should we push this out to a different milestone?

**Comment by b-kelly** [comment]
Pushing out to 2.5 then so we can cross off all the boxes for Beta 2.
