### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by mustafa0x** [StackExchange/Stacks-Editor#159]
https://github.com/StackExchange/Stacks-Editor/blob/185d3e001e84d82ddb943a05cfcfe31b9e7d5e39/src/shared/prosemirror-plugins/code-paste-handler.ts#L21

Occurs when pasting text/html content into the editor. Bundling with Vite.

**Comment by b-kelly** [comment]
Thanks for the report. I believe this is the second time this has happened now, so I've completely turned off Node polyfill support in Webpack in a1f35dd2154503a0b8b82cfd021c0e296536b8c4. This will cause us to catch this problem during development, rather than passing it downstream to our users...
