### ISSUE TITLE
bug(markdown) Applying a blockquote to a header line will remove the header hash marks and indented code

### ISSUE THREAD

**Issue by yellis** [StackExchange/Stacks-Editor#171]
**Describe the bug**
Applying a blockquote to a header line will remove the header hash marks. This will happen regardless of what (if anything) is highlighted on the line at the time when the blockquote function is activated. Works fine in RT mode.

**To Reproduce**
1. MD mode. Type in `# this is a header`
2. While on the line, `ctrl-q` or use the blockquote button
3. The header `#` disappears

Will also remove indented code formatting. Ie, this:
```
    Triage result      Questions Avg Views 
    ------------------ --------- --------- 
    Looks Good         11379     76        
    Should Be Improved 9825      66        
    Unsalvageable      4299      48     
```
Becomes this:
```
> Triage result      Questions Avg Views 
> 
> Looks Good         11379     76        
> Should Be Improved 9825      66        
> Unsalvageable      4299      48 
```

**Expected behavior**
Blockquote application in MD mode should not remove header hashes

**Screenshots**
![image](https://i.stack.imgur.com/mWVKd.gif)

**Desktop (please complete the following information):**
Windows 11 Chrome 103

**Additional context**
- https://meta.stackexchange.com/a/380318/51
- https://meta.stackexchange.com/a/363589/51

**Comment by b-kelly** [comment]
Same root issue as #70, closing this issue to keep the list tidy.
