### ISSUE TITLE
bug(markdown) Headings defined by setext underline of one character are not being formatted as headings

### ISSUE THREAD

**Issue by yellis** [StackExchange/Stacks-Editor#182]
**Describe the bug**
[Commonmark allows](https://spec.commonmark.org/0.30/#example-83) headings to be defined by setext underline - most common way is text, followed by line indented 3 or fewer spaces with at least one dash or = sign.

This is correctly transformed into a heading when moved to RT. But in MD it shows as plain text, and is only formatted as a heading when there are two chars.

**To Reproduce**
1. MD mode, Enter a line of text, and then a second line with one `=` char.
2. Observe no Header formatting
3. Switch to RT, observe header formatting
4. Switch to MD, add another `=` char, observe that the header formatting is now added

**Expected behavior**
Proper header formatting in MD mode for just one setext underline char

**Screenshots**
![demo](https://i.stack.imgur.com/ZldXe.gif)

**Desktop (please complete the following information):**
Windows 11 Chrome 103

**Additional context**
https://meta.stackexchange.com/a/380339/51

**Comment by b-kelly** [comment]
Covered under #21, closing this issue to keep the list tidy
