### ISSUE TITLE
Link insertion / editing enhancements

### ISSUE THREAD

**Issue by b-kelly** [StackExchange/Stacks-Editor#19]
Reported on [Meta.SE](https://meta.stackexchange.com/a/360047/395497). Related report [here](https://meta.stackexchange.com/a/360037/395497).

**Is your feature request related to a problem? Please describe.**

Link editing and insertion is currently confusing. The button only highlights when text has already been selected and you cannot insert a link without pre-selecting text.

> I’m not sure all users will understand how the ‘Link selection’ button works. (Hint: you have to select the text first, then the button will become enabled.)

**Describe the solution you'd like**

> Other rich text editors I use regularly have an 'Insert Link' button where you can specify both the link and the text to display.
> So something like this (excuse the bad mockup, hopefully the idea is clear):
> ![](https://i.stack.imgur.com/2GZ2i.png)
> Or enable the button at all times, and if nothing is selected, ask the user for a link (like the current editor) and insert it, with the popover visible so that users know they can edit both the link text and the link itself:
> ![](https://i.stack.imgur.com/7kq8k.png)

**Comment by aaronshekey** [comment]
Yeah, I'd like to see us move away from popovers here.  They seem to be getting in the way of text selection and the like.
