### ISSUE TITLE
Allow saving edits to a post using Ctrl-Enter like in the old editor

### ISSUE THREAD

**Issue by yellis** [StackExchange/Stacks-Editor#205]
- https://meta.stackexchange.com/a/380313/51
- https://meta.stackexchange.com/a/360075/51

Ctrl-Enter saves the post in the old editor. Request is for this to be the convention here as well.

Would need to:
- Eliminate other uses of Ctrl-Enter (exit code block and exit table)
- Wait until keybinds are [exposed in the plugin API](https://github.com/StackExchange/Stacks-Editor/blob/main/src/shared/editor-plugin.ts#L56-L57)
- Add plugin to attach to this keybind

**Comment by b-kelly** [comment]
This will need to be handled in the implementation. You can listen to key events as expected without problem - ProseMirror cancels propagation of all events it handles. In our Core implementation, you can also add a listener to the backing textarea instead, as our implementation forwards all events to it.

**Comment by yellis** [comment]
Continued on PUBPLAT-3459
