### ISSUE TITLE
Image breaking after switching to markdown mode and back

### ISSUE THREAD

**Issue by Paladise** [StackExchange/Stacks-Editor#208]
**Describe the bug**
If you insert an image using the rich-text editor, and then switch to markdown, and switch back to rich-text, the image breaks.

**To Reproduce**
1. Go to https://stackoverflow.design/product/components/editor/#textarea-content-with-tables-enabled where the example is with the image
2. Switch to markdown mode
3. Switch directly back to rich-text mode
4. See extra image details that weren't there before

**Expected behavior**
It should appear exactly as it was before.

**Screenshots**

**Original:**
![Original:](https://user-images.githubusercontent.com/53283372/181607015-f8733bf4-4b5f-4563-a2f7-3e8314954766.PNG)

**After:**
![After](https://user-images.githubusercontent.com/53283372/181607167-2e1cb1ad-4e94-473d-b48a-05aff26685c3.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 103.0.5060.114 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by b-kelly** [comment]
Oh, this is an interesting one. I can repro the issue with the following content:

```md
<img
  src="https://images.unsplash.com/photo-1556740758-90de374c12ad?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80"
  alt=""
/>
```

but **not** this content (note the lack of newline characters):

```md
<img src="https://images.unsplash.com/photo-1556740758-90de374c12ad?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=80" alt="" />
```

What seems to be happening here is that the code that attempts to remember the html formatting of the parsed markdown (e.g. `<img>` vs `<img />` vs `<img/>`) is getting tripped up by the newlines.

Thanks for the report!
