### ISSUE TITLE
Ask on Meta StackExchange Enable featured discussion Beta user's interface preference

### ISSUE THREAD

**Issue by bnhassin** [StackExchange/Stacks-Editor#209]
**[Public Interface Beta](https://meta.stackexchange.com/users/preferences/?=)**
![Screenshot_20220802-232007.jpg](https://user-images.githubusercontent.com/1473765/182483821-af93054c-551d-49f7-8e7e-c0e060358060.jpg)
#209

**Comment by b-kelly** [comment]
Could you provide more info as to what you're asking here? Please keep in mind that this repo does not take bugs/enhancements for the Stack Exchange network. Closing until more details are given.
