### ISSUE TITLE
Undo/Redo buttons are vertically stacked in Markdown mode on narrow screens

### ISSUE THREAD

**Issue by Justin-MSE** [StackExchange/Stacks-Editor#212]
**Describe the bug**
When using Markdown mode on narrow screens, the Undo/Redo buttons are vertically stacked. This is not the case in rich text mode, where the Undo/Redo buttons appear side-by-side, like in the old editor.

**To Reproduce**
1. On a narrow screen width, go to Markdown mode.
2. Undo/Redo buttons will be vertically stacked.

Note that the screen has to be narrow enough till the Undo/Redo buttons become vertically stacked. At least on Chrome for Windows 11, reducing the screen width just enough to see the Undo/Redo buttons does not result in the buttons being vertically stacked. It happens at a slightly more narrower screen width. Strangely, this is not the case with the [demo editor](https://editor.stackoverflow.design/), where the issue occurs immediately once the Undo/Redo buttons are visible.

**Expected behavior**
The side-by-side layout should be made consistent in both modes.

**Screenshots**
Markdown mode (vertically stacked):

[![enter image description here][1]][1]

Rich text mode (side-by-side layout):

[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/i5W4x.png
  [2]: https://i.stack.imgur.com/wNOH9.png

**Desktop (please complete the following information):**
 - Chrome 104.0.5112.81 on Windows 11

**Smartphone (please complete the following information):**
 - Chrome 104.0.5112.81 for Android

**Additional context**
Also on MSE: [Undo/Redo buttons are vertically stacked in Markdown mode on narrow screens](https://meta.stackexchange.com/questions/381213/undo-redo-buttons-are-vertically-stacked-in-markdown-mode-on-narrow-screens)

**Comment by b-kelly** [comment]
Looks like this was accidentally fixed in my latest commit, but the demo editor was not up-to-date due to a Netlify deploy issue. I updated some deploy settings on Netlify's side of things, so now our demo should reflect the current state of the `main` branch.

Closing as fixed.
