### ISSUE TITLE
Dragging/dropping or pasting an image in rich text mode results in the image uploader showing the same image twice

### ISSUE THREAD

**Issue by Justin-MSE** [StackExchange/Stacks-Editor#213]
**Describe the bug**
Dragging/dropping or pasting an image in rich text mode results in the same image being shown twice (side-by-side) in the image uploader.

**To Reproduce**
1. Switch to rich text mode.
2. Click inside the editor to activate it (you should see a blue border around the editor).
3. Drag and drop, or paste, an image into the editor.
4. You should see that image being shown twice (side-by-side) in the image uploader.

Note that if the editor has not been activated before dragging/dropping an image, only a single image is shown in the image uploader, as intended.

**Expected behavior**
After dragging/dropping or pasting an image in the editor, the image should only be shown once in the image uploader (in rich text mode).

**Screenshots**

[![An image being dropped into the editor and resulting in two side by side images][1]][1]

  [1]: https://i.stack.imgur.com/wzAfp.gif

**Desktop (please complete the following information):**
 - Chrome 104.0.5112.81 on Windows 11

**Additional context**
Also on MSE: [Dragging/dropping or pasting an image in rich text mode results in the image uploader showing the same image twice](https://meta.stackexchange.com/questions/381109/dragging-dropping-or-pasting-an-image-in-rich-text-mode-results-in-the-image-upl)

**Comment by b-kelly** [comment]
Confirmed that I can only repro this in rich-text mode and not markdown mode. That's good info to have as it narrows down the possible culprits quite a bit.
