### ISSUE TITLE
Double the expected thumbnails showing on image pasting

### ISSUE THREAD

**Issue by allejo** [StackExchange/Stacks-Editor#219]
**Describe the bug**

Whenever I paste an image on both SO and the [demo editor](https://editor.stackoverflow.design/), I get twice the expected number of thumbnails of it.

**To Reproduce**

1. Go to either SO or the [demo editor](https://editor.stackoverflow.design/)
2. Paste a screenshot taken from your OS
3. See double the thumbnails

**Expected behavior**

There should be exactly half the number of current thumbnails

**Screenshots**

![image](https://user-images.githubusercontent.com/1246453/187523935-bef787dd-b3d8-4e94-8fd4-57e7c21686c9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 104.0.5112.102

**Comment by Justin-MSE** [comment]
Hi @allejo. I've reported this recently in more detail: https://github.com/StackExchange/Stacks-Editor/issues/213. This also happens when dragging/dropping an image.

**Comment by allejo** [comment]
Closing as a duplicate of #213, thanks @Justin-MSE!
