### ISSUE TITLE
bug(markdown) Code blocks surrounded by single backtick then triple backticks

### ISSUE THREAD

**Issue by yellis** [StackExchange/Stacks-Editor#230]
**Describe the bug**
Pasting fenced code block into inline code block results in the following being saved
![image](https://user-images.githubusercontent.com/1366941/198203903-54271db7-9b31-4e1d-9af0-d07f43599fb1.png)

A side issue here might be that the inline code block menu button has much more prominence than the fenced code block button, so users go to it first and dont think of fenced code block (could also be something that the interface is expecting too much from the user here).

**To Reproduce**
1. Create inline code block (can use menu)
2. Paste in fenced code block
3. Note: the inline code block ticks are still there, and if saved, will be orphaned ticks surrounding the fenced code block.

**Expected behavior**
Pasting a fenced code block into an inline code block results in only the fenced code block being inserted, and the preceding and following inline code block ticks being removed.

**Screenshots**
![https://i.stack.imgur.com/F9la7.gif](https://i.stack.imgur.com/F9la7.gif)

**Desktop (please complete the following information):**
Windows 10 Chrome Latest

**Additional context**
[Code blocks surrounded by single backtick then triple backticks](https://meta.stackoverflow.com/questions/421118/code-blocks-surrounded-by-single-backtick-then-triple-backticks). Answer on that page has further repro info.

**Comment by philBrown** [comment]
Is this not deployed? Still seeing heaps of questions coming in with 
````md
`
```
some code
```
`
````
