### ISSUE TITLE
Try to embed image in 

### ISSUE THREAD

**Issue by mdobreva** [StackExchange/Stacks-Editor#242]
I`m trying to embed image and for the first time it is visualized as it expected. Then I try to load the content in the Stack editor and the image is not visualized correctly. It is the same when I tested to upload image in https://editor.stackoverflow.design/.

1. Go to https://editor.stackoverflow.design/
2. Click on Image, then click Browse, select some image and click Add Image
3. Switch to Mark Down mode
4. Then switch again to Rich Text mode and the image doesn`t rendered correctly.

![image](https://user-images.githubusercontent.com/7443122/230627187-7695ae63-dec4-4a47-a097-3fa22d11af19.png)

Then I switched to Markdown mode 
![image](https://user-images.githubusercontent.com/7443122/230627313-1f6eb05d-ed5b-4f25-9f2e-8c8286a493b7.png)

And the again to Rich text Editor and the image is not rendered correctly
![image](https://user-images.githubusercontent.com/7443122/230627589-e3a18932-e991-452b-a2de-42fc0f87e3be.png)

**Comment by mdobreva** [comment]
Hello @giamir, I am afraid you misunderstand my issue.  In my particular use case, I do not want to upload the image to a hosting solution.  In stead, I want the image to be embedded into the markdown content as BASE64 encoded.  So far this works as expected, and if I convert the markdown content to HTML with this embedded BASE64 content, the generated HTML works, too. 

The problem here is that Stacks Editor does not render the image from embedded BASE64 content, if the markdown with such embedded images is loaded into the editor.

**Comment by giamir** [comment]
For our internal use cases we don't need to support embedded base64 images. The default behavior of the editor consider data urls (e.g. `data:image/png;base64,<base64>`) invalid links. To change that behavior you can pass your own link validator:
https://github.com/StackExchange/Stacks-Editor/blob/main/src/shared/view.ts#L99
Passing the following stacks editor configuration will make all text a valid link (including data urls). This will instruct the editor to parse embed images as you expect to.
```
{
  parserFeatures: {
    validateLink: () => true
  }
}
```
