### ISSUE TITLE
Enter key oddities in Firefox

### ISSUE THREAD

**Issue by b-kelly** [StackExchange/Stacks-Editor#25]
Reported on [Meta.SE](https://meta.stackexchange.com/a/360036/395497).

**Describe the bug**

> 1. Start in Markdown mode
> 1. Write any text
> 2. Hit the Enter button
> 
> I expect the editor to take my cursor to the next line, but it doesn't. I need to hit Enter another time for the cursor to move, but when I restart typing words, they appear on the *third* line. In other words, the <kbd>Enter</kbd> button works, it's just the cursor that's lagging.
> 
> Reproducible in Firefox 86, but not in Chrome 88.

**Comment by hamvocke** [comment]
This sounds oddly familiar. There was a bug in Firefox 86 where this kind of behavior started popping up in `code` blocks. I've reported this issue upstream and the ProseMirror authors came up with a workaround. I'd suspect dropping a new release will fix this issue. See #13

**Comment by b-kelly** [comment]
I tested the original bug and it seemed fixed, but there were still some semi-related issues that I could see, so I left the bug intact to force us to revisit.

**Comment by b-kelly** [comment]
Testing this again, it looks like all issues have been resolved. Closing in favor of adding new issues when any new bugs are noticed.
