### ISSUE TITLE
Distribution code is missing from repo

### ISSUE THREAD

**Issue by BSarmady** [StackExchange/Stacks-Editor#253]
**The problem**
I was going to use this editor in a website after reading document, I noticed:
- path to script is specified as "path/to/node_modules/@stackoverflow"
    looking at SO website I see that during render of the editor no requests are sent to backend, which I assume no node_modules are required.

- I could not find `dist` folder neither in repo nor in releases.

Even though I'm a full stack programmer, my stack doesn't include Typescript, node.js or npm. 

**The Solution**
I appreciate if you could include your compiled scripts (package including js, css, and all required files) in dist folder or releases; Something like [this](https://github.com/twbs/bootstrap/tree/main/dist) and also [this](https://github.com/twbs/bootstrap/releases/download/v5.3.1/bootstrap-5.3.1-dist.zip) a the bottom of [this release page](https://github.com/twbs/bootstrap/releases/tag/v5.3.1)

**Alternatives I've considered**
For now I just downloaded [SO's 11 years old pagedown](https://github.com/StackExchange/pagedown) that has been inactive for about 6 years.

**Additional context**
To me, I does not seem like a good idea to download about 4GB node and npm and their default packages and install them to my OS drive (which I cannot change its location, btw) 

I'm sure you wouldn't appreciate if you had to download source code for OS, Open-office, Java, node.js, npm, your code editor of choice, Thunderbird, Firefox, Chrome and compile them to be able to use them

**Comment by giamir** [comment]
Thanks for raising this issue.

We are actually shipping the distribution code as part of our packages. If you are not familiar with npm you can pull them down directly from `unpkg.com`. See the following example linking to the distribution assets hosted in `unpkg.com`:
```html
<!--include Stacks -->
<link rel="stylesheet" href="//unpkg.com/@stackoverflow/stacks/dist/css/stacks.css" />
<!-- include the bundled styles -->
<link
    rel="stylesheet"
    href="//unpkg.com/@stackoverflow/stacks-editor/dist/styles.css"
/>

<div id="editor-container"></div>

<!-- highlight.js is not included in the bundle, so include it as well if you want it -->
<script src="//unpkg.com/@highlightjs/cdn-assets@latest/highlight.min.js"></script>
<!--include Stacks -->
<script src="//unpkg.com/@stackoverflow/stacks/dist/stacks.min.js"></script>
<!-- include the bundle -->
<script src="//unpkg.com/@stackoverflow/stacks-editor/dist/app.bundle.js"></script>

<!-- initialize the editor -->
<script>
    new window.stacksEditor.StacksEditor(
        document.querySelector("#editor-container"),
        "*Your* **markdown** here",
        {}
    );
</script>
```

Closing this issue.

**Comment by BSarmady** [comment]
Thank you for pointing me to the unpkg. and the JS and CSS files that include stylesheet and packaged Javascript for entire stackoverflow website. I am interested in just the editor code.
