### ISSUE TITLE
Triple-click selects the entire text in Markdown mode

### ISSUE THREAD

**Issue by b-kelly** [StackExchange/Stacks-Editor#27]
Reported on [Meta.SE](https://meta.stackexchange.com/a/360115/395497).

**Describe the bug**

> It's a standard practice in modern text fields to double-click in order to select a single word and triple-click to select a single **paragraph**. This has worked in the old editor, works in the Rich Text editor, but does not work in Markdown mode and the entire text gets selected instead.
> 
> ![Selecting paragraph in Rich Text vs Markdown mode](https://i.stack.imgur.com/akYIf.gif)

**Expected behavior**

The paragraph the cursor is currently in is selected, not the entirety of the text.

**Comment by LunarWatcher** [comment]
I'm genuinely disappointed several high-profile bugs surrounding basic functionality haven't been fixed after almost a year, even though the editor is continuing its rollout.

As a mod, the lack of triple click to select a paragraph is an enormous pain point when editing templates in review suspensions, and the continued rollout makes this bug, along several others, incredibly frustrating
