### ISSUE TITLE
Pasting content from external editors contains invisible newline characters

### ISSUE THREAD

**Issue by b-kelly** [StackExchange/Stacks-Editor#36]
Reported on [Meta.SE](https://meta.stackexchange.com/a/360117/395497)

**Describe the bug**

> Copying quoted text from Markdown mode into a text editor like Visual Studio Code and back invisibly breaks the Markdown to insert extra line breaks between the lines of the quote.  Toggling back and forth between rich text and Markdown reveals the extra line breaks.
> 
> ![Copy-pasting between windows inserting linebreaks](https://i.stack.imgur.com/BGzWM.gif)

**To Reproduce**

1. Type the following in markdown mode:

```
> quote a
> 
> quote b
```

2. Toggle to rich text mode and observe it is a single blockquote.
3. Paste the content in an external editor
   * reproduced with both VS Code and Notepad++
4. Copy and paste that content back into markdown mode
5. Toggle to rich text mode and observe each line is a separate block quote

**Comment by dancormier** [comment]
I tried to reproduce this on both Windows and Mac OS, but no dice. Is this resolved @b-kelly?

**Comment by b-kelly** [comment]
Agreed. I cannot repro the issue with either VS Code or Notepad++ (as specified in the bug report. I'm willing to call this one resolved. We can reopen later if it is still an issue.
