### ISSUE TITLE
Toggle heading shortcut broken in rich text mode

### ISSUE THREAD

**Issue by b-kelly** [StackExchange/Stacks-Editor#45]
Reported on [Meta.SE](https://meta.stackexchange.com/a/360119/395497)

**Describe the bug**

> ### Pressing <kbd>Ctrl</kbd>+<kbd>H</kbd> does not *toggle* Heading in Rich Text mode
> 
> - In the old editor, it would _cycle_ between several Headings.
> - In the Markdown mode of the new editor, it _toggles_ between Heading1 and no heading.
> - However, in the Rich Text editor, it only works one way. Pressing <kbd>Ctrl</kbd>+<kbd>H</kbd> for a second time opens the browser's history tab in Chrome.

**Comment by dancormier** [comment]
Even better, on Mac OS, `⌘`+`H` hides the browser window in the Rich Text editor. Fun!

FWIW, markdown works as expected.

**Comment by yellis** [comment]
@b-kelly you marked this as Done, but I just tried it, and ctrl-h in chrome still opens the history tab, when in markdown mode.

**Comment by b-kelly** [comment]
Unable to repro. Works ok in Chrome 103 on Win 10 on both the reference editor and locally. Are you able to provide repro steps?

https://user-images.githubusercontent.com/14169651/178530316-7d2d0b49-5703-4d01-9c62-f9c6943460f4.mp4

**Comment by dancormier** [comment]
Same here on Mac OS in Chrome 103 and Firefox 102. @yellis when you experience the issue, is the editor focused?

**Comment by yellis** [comment]
It wasn't working yesterday. I promise.

But I cant repro now. So 🤷
