### ISSUE TITLE
Add rich text insert equivalents of all markdown-only nodes

### ISSUE THREAD

**Issue by b-kelly** [StackExchange/Stacks-Editor#51]
Related report on [Meta.SE](https://meta.stackexchange.com/a/360588/395497)

**Is your feature request related to a problem? Please describe.**

There is no way to create many custom markdown-only nodes in rich-text mode. These include:
* spoilers
* tag badges
* html-only nodes like `<sub>`, `<sup>`, `<kbd>`

**Describe the solution you'd like**

Add in a way to add these via rich text. Shortcuts are a given, but perhaps we could add some buttons to the UI somewhere that isn't overly intrusive or cluttered.

**Comment by tmcentee** [comment]
@pxeger Got it covered. Thanks for the reminder of that one!

**Comment by septatrix** [comment]
Also `<details>`/`<summary>`

**Comment by pxeger** [comment]
@septatrix StackExchange Markdown doesn't currently support `<details>`: they just act like nothing's there, so I don't think they'll get support in the rich text editor any time soon.

**Comment by septatrix** [comment]
> @septatrix StackExchange Markdown doesn't currently support `<details>`: they just act like nothing's there, so I don't think they'll get support in the rich text editor any time soon.

Fair enough. For reference there is a corresponding [meta.stackexchange.com question about `<details>` support](https://meta.stackexchange.com/questions/374236/can-questions-support-the-details-tag) (with some more related questions linked in a comment).

**Comment by b-kelly** [comment]
@septatrix You can see all the currently supported tags on SE sites [here](https://meta.stackexchange.com/questions/1777/what-html-tags-are-allowed-on-stack-exchange-sites).

As a both a developer and user, I'm conflicted about supporting `<details>`. As a user, I'd _love_ to be able to use these in posts. I pretty strongly abuse their use in GitHub when posting large or many images. As a developer, oh man I would _not_ be looking forward to supporting rendering these in rich-text mode. 😉
