### ISSUE TITLE
Pressing down arrow key in last table cell sends the cursor to the first cell

### ISSUE THREAD

**Issue by b-kelly** [StackExchange/Stacks-Editor#55]
Reported on [Meta.SE](https://meta.stackexchange.com/a/361734/395497)

**Describe the bug**

> The video below shows what happens if one holds the  <kbd>↓</kbd> key. I think it'd be preferable if it doesn't loop around, especially since holding the  <kbd>↑</kbd> key doesn't loop.
> 
> [![enter image description here](https://i.stack.imgur.com/oRrBw.gif)](https://i.stack.imgur.com/oRrBw.gif)
> 
> Markdown used in the demo:
> 
> ```
> | Column A | Column B |
> | --- | --- |
> |  | A margin call occurs when the value of an investor's |
> | [Federal call](https://www.investopedia.com/terms/f/federal-call.asp) | A federal call is a legally mandated margin call pursuant to Regulation T. Investors will receive a federal call when their margin account lacks sufficient equity to meet the initial margin requirement for new, or initial, purchases. |
> ```
> 
> Tested with Windows 7 SP1 x64 Ultimate and Google Chrome 88.0.4324.190 (Official Build) (64-bit).

**Comment by double-beep** [comment]
I'm no longer able to reproduce the problem in Chrome 100.

**Comment by yellis** [comment]
@b-kelly I cant repro this exact problem. However, maybe related, if I am in a table and the table is at the end of the doc, there is no way to get below the table in rich text mode.
