### ISSUE TITLE
No preview when adding image for the second time

### ISSUE THREAD

**Issue by WouterDeKort** [StackExchange/Stacks-Editor#65]
**Describe the bug**

Browsing for an image, cancelling the image upload and then browsing for the same image does not show the image preview.

**To Reproduce**
1. Select the Image icon
2. Click on 'Browse'
3. Select a local image
4. Click on 'Cancel'
5. Select the Image icon
6. Click on 'Browse'
7. Select the same image as in step 3

**Expected behavior**
I expect the image to be shown as a preview and be able to 

**Screenshots**

![Cancel-Add-Image-Bug](https://user-images.githubusercontent.com/1763043/114533703-79379500-9c4e-11eb-99ef-a367ef4381d4.gif)

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Version 89.0.4389.114

**Comment by b-kelly** [comment]
Fixed in #67
