### ISSUE TITLE
GitHub-like list-bullet completion in markdown mode

### ISSUE THREAD

**Issue by hamvocke** [StackExchange/Stacks-Editor#68]
GitHub recently [introduced](https://github.blog/changelog/2020-12-15-markdown-list-syntax-now-autocompleted/) markdown list completion. In practice this means if you type a list item in markdown, then hit enter, the next line will automatically start with the same list bullet character as your current line.

I can see this being useful for our markdown-mode, too. Maybe as an option that can be passed based on preference. Personally, I'm in the camp of keeping markdown-mode bare-bones as I want to completely be in charge of what's happening, no smarts, no bells, no whistles. But I acknowledge that my opinion isn't necessarily everyone else's opinion so I figured we could discuss :)

**Comment by b-kelly** [comment]
I'm personally in the camp of "this functionality is slightly annoying", but I wouldn't be against adding it if there was sufficient demand. Adding the "help wanted" label in case anyone wants to pick this up.

**Comment by hamvocke** [comment]
Duplicate of #87
