### ISSUE TITLE
How do setup image upload?

### ISSUE THREAD

**Issue by iwasherefirst2** [StackExchange/Stacks-Editor#82]
**Is your feature request related to a problem? Please describe.**
I cannot upload images with the editor:
![image](https://user-images.githubusercontent.com/1765602/132481138-23c798c0-0504-444a-917c-f7db8666aa7c.png)

**Describe the solution you'd like**
It would be awesome if there would be an explanation how to use the image upload function. It just fails and I don't know where to specify the route where to upload the image.

**Describe alternatives you've considered**
I tried to find anything in https://github.com/StackExchange/Stacks-Editor/blob/main/src/stacks-editor/editor.ts that leads me  to the section where the image upload is handled, but I could not find anything.

**Comment by b-kelly** [comment]
Any consumer customizable options can be found on the exported [`StacksEditorOptions`](https://github.com/StackExchange/Stacks-Editor/blob/main/src/stacks-editor/editor.ts#L27) interface. One day I'll spin up some automated type-generated documentation to help assist with this, but until then you'll need to dive into the interfaces a bit.

Image uploads are handled by `StacksEditorOptions.imageUpload.handler` which is of type [`ImageUploadHandlerCallback`](https://github.com/StackExchange/Stacks-Editor/blob/9c61c662ec18a5486442f64b0c53d80f5c1b0553/src/shared/prosemirror-plugins/image-upload.ts#L19-L44). A typical sample method can be found [here](https://github.com/StackExchange/Stacks-Editor/blob/9c61c662ec18a5486442f64b0c53d80f5c1b0553/src/shared/prosemirror-plugins/image-upload.ts#L52), with a much more ~~overengineered~~ specific implementation found on our [demo page](https://github.com/StackExchange/Stacks-Editor/blob/9c61c662ec18a5486442f64b0c53d80f5c1b0553/site/index.ts#L71).

I've added #83 as a follow up issue to generate documentation for all exposed types.
