### ISSUE TITLE
Keyboard shortcuts don't work with Caps Lock enabled

### ISSUE THREAD

**Issue by zcoop98** [StackExchange/Stacks-Editor#90]
**Describe the bug**
Keyboard shortcuts don't work when Caps Lock is enabled. 

**To Reproduce**
1. Start composing a post in the editor
2. Enable Caps Lock
3. Attempt to embolden text with <kbd>Ctrl+B</kbd> or create a block quote with <kbd>Ctrl+Q</kbd>
4. Observe the shortcut does nothing, and associated ribbon/ menu bar icons (eg. **B** icon for bold) do not highlight
5. Turn off Caps Lock
6. Try shortcut(s) again
7. Observe that keyboard shortcuts now work as normal, and associated ribbon icons highlight as expected when a given tool is active

**Expected behavior**
Keyboard shortcuts, such as <kbd>Ctrl+I</kbd> to italicize, <kbd>Ctrl+B</kbd> to embolden, <kbd>Ctrl+Q</kbd> to create a quote block, <kbd>Ctrl+K</kbd> for code, etc., should work when Caps Lock is active.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94.0.4606.81

**Comment by dancormier** [comment]
Note: This is a Windows-specific issue. Caps Locks does not interfere with keyboard shortcuts on Mac OS.

**Comment by b-kelly** [comment]
Looks like the official advice for this is to add each keybind twice - once for lower and once for upper...

References:
* https://github.com/ProseMirror/prosemirror/issues/895
* https://discuss.prosemirror.net/t/undo-redo-broken-with-caps-lock-on-website-demo/4068
* https://github.com/ProseMirror/prosemirror-example-setup/blob/master/src/keymap.js#L60-L61
