### ISSUE TITLE
Star lists are rendered as italics

### ISSUE THREAD

**Issue by LunarWatcher** [StackExchange/Stacks-Editor#95]
**Describe the bug**
Star lists (or whatever they're called; `<ul>`s defined with `*` instead of `-`) in quotes are previewed as italics. They still render as bullet lists, so the issue is with the editor.

**To Reproduce**
```
> * One (this point is italic)
> * Two
> * Three

This is italic, and because of a lack of termination (#21), everything after is italic

<!-- * but a comment terminates the italic -->

Regular text
```

[Rendered output + demo](https://meta.stackexchange.com/a/374506/332043)

**Expected behavior**
No italics

**Screenshots**
![image](https://user-images.githubusercontent.com/29489988/147290962-15360449-63ac-4cd1-b786-f0a38114297c.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2
 - Browser: Firefox 
 - Version: 95.0.1

**Smartphone (please complete the following information):**
(Not tested, this issue presumably stems from the same cause as #21)

**Comment by yellis** [comment]
@b-kelly I cant repro any longer on the linked meta issue. FixeD?

**Comment by b-kelly** [comment]
This issue is also covered under #21, so I'm closing this issue to keep everything tidy.
