### ISSUE TITLE
Markdown mode: Bold + italics on text block cause the rest of the document to appear bold and italicized

### ISSUE THREAD

**Issue by adunndevster** [StackExchange/Stacks-Editor#97]
**Describe the bug**
*My text* - works great!
**My text** - works great!
***My text*** - Causes the beginning of the block, all the way to the rest of the document to appear bold and italicized. Not just the intended block.

**To Reproduce**
1. Go to https://editor.stackoverflow.design/
2. Make sure you are in mark down mode
3. replace the document text with "The quick brown fox jumps over the lazy dog."
4. Bold AND italicize "quick brown fox". (i.e. "The ***quick brown fox*** jumps over the lazy dog."
5. Notice that from that block, to the end of the document is bold and italicized.

**Expected behavior**
We only want the intended block to be bolded and italicized.

@b-kelly, I'm happy to try and fix this, and contribute. I've cloned the project and have been digging around. If you have a direction to point me that would be even better.

**Comment by b-kelly** [comment]
In markdown mode, we basically treat the entire node as a `code_block` and use `highlight.js`'s syntax highlighting. The syntax [highlighting rules](https://github.com/highlightjs/highlight.js/blob/main/src/languages/markdown.js) for markdown are not quite 100% commonmark compliant. This is something we wish to tackle by contributing upstream, but we haven't had the opportunity to prioritize this work yet. I already have this tracked in #21, so I'm going to close this issue for the time being.
